services:

  index:
    image: ghcr.io/acoustid/acoustid-index:v2022.02.03
    ports:
      - "127.0.0.1:16080:6080"

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:16379:6379"

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:19000:9000"
      - "127.0.0.1:19001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: notreallyapassword

  postgres:
    image: quay.io/acoustid/postgresql:master
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - ./scripts/dev/create-db.sh:/docker-entrypoint-initdb.d/setup_db.sh
      - ./database/sql:/mnt/acoustid/sql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notreallyapassword
      ACOUSTID_SQL_DIR: /mnt/acoustid/sql
