version: "3"
services:

  index:
    image: ghcr.io/acoustid/acoustid-index:v2022.02.03
    ports:
      - "127.0.0.1:16080:6080"

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:16379:6379"

  postgres:
    image: quay.io/acoustid/postgresql:master
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - ./scripts/dev/create-db.sh:/docker-entrypoint-initdb.d/setup_db.sh
      - ./database/sql:/mnt/acoustid/sql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      ACOUSTID_SQL_DIR: /mnt/acoustid/sql
