// Copyright (C) 2016  Lukas Lalinsky
// Distributed under the MIT license, see the LICENSE file for details.

// Package chromaprint provides a number of utility functions for working with audio fingerprints generated by Chromaprint.
package chromaprint
