package chromaprint

import (
	"bytes"
	"encoding/json"
	"github.com/pkg/errors"
	"math"
	"os/exec"
	"strconv"
	"strings"
	"time"
)

type FingerprintResult struct {
	*Fingerprint
	Duration time.Duration
}

func FingerprintFile(path string, duration int) (FingerprintResult, error) {
	cmd := exec.Command("fpcalc", "-length", strconv.Itoa(duration), "-json", path)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	var result FingerprintResult

	err := cmd.Run()
	if err != nil {
		return result, errors.Wrapf(err, "fpcalc failed: %v", strings.TrimSpace(stderr.String()))
	}

	var output struct {
		Duration    float64 `json:"duration"`
		Fingerprint string  `json:"fingerprint"`
	}

	err = json.Unmarshal(stdout.Bytes(), &output)
	if err != nil {
		return result, errors.Wrap(err, "invalid JSON output from fpcalc")
	}

	result.Duration = time.Duration(math.Floor(1000*output.Duration+0.5)) * time.Millisecond
	result.Fingerprint, err = ParseFingerprintString(output.Fingerprint)
	if err != nil {
		return result, errors.Wrap(err, "failed to parse the fingerprint generated by fpcalc")
	}

	return result, nil
}
